# Generated by Django 2.2.1 on 2019-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='data',
            new_name='data_pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_sistema',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='grau_pagamento',
            field=models.CharField(choices=[('-----', '-----'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestre', 'Mestre')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
