# Generated by Django 2.2.1 on 2019-08-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_categoria_parcela_mestrado_parcela_pos_graduacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='parecela_mestrado',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='financas.Parcela_Mestrado'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='parecela_posgraduacao',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='financas.Parcela_Pos_Graduacao'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='financas.Categoria'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_sistema',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.CharField(max_length=10),
        ),
    ]
