# Generated by Django 2.2.1 on 2019-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_auto_20190627_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='grau_pagamento',
            field=models.CharField(choices=[('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado')], max_length=20),
        ),
    ]
