# Generated by Django 2.2.1 on 2019-08-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_auto_20190801_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.CharField(max_length=13),
        ),
    ]
