# Generated by Django 2.2.1 on 2019-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_auto_20190802_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(max_length=13),
        ),
    ]
