# Generated by Django 3.0.1 on 2020-01-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_auto_20190809_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.CharField(max_length=13),
        ),
    ]
