# Generated by Django 3.0.1 on 2020-01-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0016_estatistica_opcao'),
        ('financas', '0006_auto_20200106_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
            preserve_default=False,
        ),
    ]
