# Generated by Django 3.0.1 on 2020-01-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_pagamento_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='valor',
        ),
    ]
