# Generated by Django 2.2.1 on 2019-06-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano_Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Semestre')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
    ]
