# Generated by Django 2.2.1 on 2019-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0002_ano_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grau_academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
