# Generated by Django 2.2.1 on 2019-06-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0004_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ano_semestre',
            name='semestre',
        ),
    ]
