# Generated by Django 2.2.1 on 2019-06-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0006_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='ano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Ano'),
            preserve_default=False,
        ),
    ]
