# Generated by Django 2.2.1 on 2019-06-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0007_semestre_ano'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ano_Semestre',
        ),
    ]
