# Generated by Django 2.2.1 on 2019-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0008_delete_ano_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
