# Generated by Django 2.2.1 on 2019-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0009_auto_20190626_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento_semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('valor', models.CharField(blank=True, default='--', max_length=12, null=True)),
            ],
        ),
    ]
