# Generated by Django 2.2.1 on 2019-07-10 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0010_pagamento_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grau_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Grau_academico')),
                ('nome', models.CharField(max_length=190)),
            ],
        ),
        migrations.AlterField(
            model_name='instituicao_superior',
            name='nome',
            field=models.CharField(max_length=190),
        ),
    ]
