# Generated by Django 2.2.1 on 2019-07-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0011_auto_20190710_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidade',
            name='grau_academico',
        ),
        migrations.AddField(
            model_name='especialidade',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
            preserve_default=False,
        ),
    ]
