# Generated by Django 2.2.1 on 2019-08-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0012_auto_20190710_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento_semestre',
        ),
    ]
