# Generated by Django 2.2.1 on 2019-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0014_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao_Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
    ]
