# Generated by Django 2.2.1 on 2019-06-26 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(blank=True, default='--', max_length=200, null=True)),
                ('nome_mae', models.CharField(blank=True, default='--', max_length=200, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12)),
                ('naturalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Provincias')),
                ('data_nascimento', models.DateField()),
                ('bi', models.CharField(max_length=20, unique=True)),
                ('estado_civil', models.CharField(choices=[('Solteiro (a)', 'solteiro (a)'), ('Casado (a)', 'casado (a)'), ('Divorciado (a)', 'Divorciado (a)'), ('Viuvo (a)', 'viuvo (a)')], max_length=20)),
                ('residencia', models.CharField(blank=True, default=' ', max_length=90, null=True)),
                ('telefone', models.CharField(blank=True, default='--', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, default='cpppgl_uan@gmail.com', max_length=60, null=True)),
            ],
        ),
    ]
