# Generated by Django 2.2.1 on 2019-06-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Instituicao_superior')),
                ('graduado', models.CharField(blank=True, max_length=90, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=90, null=True)),
                ('data_conclusao', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_estudante', models.CharField(blank=True, max_length=30, null=True)),
                ('nota_final', models.CharField(blank=True, max_length=2, null=True)),
                ('data_inscricao', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
