# Generated by Django 2.2.1 on 2019-06-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('numero_estudante', models.CharField(max_length=10)),
                ('ano_lectivo', models.CharField(blank=True, max_length=20, null=True)),
                ('curso', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Pós-Graduação', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Especialidade', 'Especialidade')], max_length=20)),
            ],
        ),
    ]
