# Generated by Django 2.2.1 on 2019-06-26 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_estudante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Estudante')),
                ('instituicao', models.CharField(blank=True, default='--', max_length=190, null=True)),
                ('funcao', models.CharField(blank=True, default='--', max_length=190, null=True)),
                ('area_profissional', models.CharField(blank=True, default='--', max_length=120, null=True)),
                ('ano_experiencia', models.CharField(blank=True, default='--', max_length=9, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
