# Generated by Django 2.2.1 on 2019-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_estudante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, default='--', max_length=20, null=True)),
                ('carga_horaria', models.CharField(blank=True, max_length=20, null=True)),
                ('ano', models.CharField(choices=[('ANO I', 'ANO I'), ('ANO II', 'ANO II'), ('ANO III', 'ANO III')], max_length=20)),
                ('semestre', models.CharField(choices=[('Semestre I', 'Semestre I'), ('Semestre II', 'Semestre II'), ('Semestre III', 'Semestre III'), ('Semestre IV', 'Semestre IV')], max_length=20)),
                ('docente', models.CharField(blank=True, default='--', max_length=100, null=True)),
            ],
        ),
    ]
