# Generated by Django 2.2.1 on 2019-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao_superior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, default=' ', max_length=20, null=True)),
                ('localidade', models.CharField(blank=True, default=' ', max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='ano_lectivo',
            new_name='data_conclusao',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='provincia',
        ),
        migrations.AddField(
            model_name='estudante',
            name='especialidade',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='graduado',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='nota_final',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='universidade',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='residencia',
            field=models.CharField(blank=True, default=' ', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='numero_estudante',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Bengo', 'Bengo'), ('Benguela', 'Benguela'), ('Bié', 'Bié'), ('Cabinda', 'Cabinda'), ('Cunene', 'Cunene'), ('Huambo', 'Huambo'), ('Huila', 'Huila'), ('Cuando kubango', 'Cuando kubango'), ('Cuanza norte', 'Cuanza norte'), ('Cuanza sul', 'Cuanza sul'), ('Lunda Norte', 'Lunda Norte'), ('Lunda sul', 'Lunda sul'), ('Malange', 'Malange'), ('Moxico', 'Moxico'), ('Namibe', 'Namibe'), ('Uige', 'Uige'), ('Zaire', 'Zaire')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
