# Generated by Django 2.2.1 on 2019-06-26 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_profissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo_Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Semestre')),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Ano_Semestre')),
                ('nome', models.CharField(blank=True, default='--', max_length=190, null=True)),
                ('sigla_codigo', models.CharField(blank=True, default='--', max_length=190, null=True)),
                ('Horas', models.CharField(blank=True, default='--', max_length=10, null=True)),
                ('credito', models.CharField(blank=True, default='--', max_length=9, null=True)),
            ],
        ),
    ]
