# Generated by Django 2.2.1 on 2019-06-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0004_especialidade'),
        ('secretaria', '0004_modulo_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo_disciplina',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Especialidade'),
        ),
    ]
