# Generated by Django 2.2.1 on 2019-06-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_auto_20190623_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Estudante')),
                ('instituicao', models.CharField(blank=True, default='--', max_length=90, null=True)),
                ('funcao', models.CharField(blank=True, default='--', max_length=90, null=True)),
                ('area_profissional', models.CharField(blank=True, default='--', max_length=120, null=True)),
                ('ano_experencia', models.CharField(blank=True, default='--', max_length=9, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='estudante',
            name='data_inscricao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='universidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Instituicao_superior'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Provincia'),
        ),
    ]
