# Generated by Django 2.2.1 on 2019-06-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_auto_20190623_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissao',
            old_name='zona',
            new_name='localizcao',
        ),
        migrations.RemoveField(
            model_name='instituicao_superior',
            name='localidade',
        ),
        migrations.AlterField(
            model_name='profissao',
            name='funcao',
            field=models.CharField(blank=True, default='--', max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='instituicao',
            field=models.CharField(blank=True, default='--', max_length=190, null=True),
        ),
    ]
