# Generated by Django 2.2.1 on 2019-06-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_modulo_disciplina_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo_disciplina',
            name='estado',
            field=models.CharField(blank=True, default='Ativado', max_length=19, null=True),
        ),
    ]
