# Generated by Django 2.2.1 on 2019-06-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_modulo_disciplina_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Ano'),
        ),
    ]
