# Generated by Django 2.2.1 on 2019-06-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_auto_20190623_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissao',
            old_name='ano_experencia',
            new_name='ano_experiencia',
        ),
    ]
