# Generated by Django 2.2.1 on 2019-06-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_auto_20190624_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissao',
            old_name='localizcao',
            new_name='localizacao',
        ),
    ]
