# Generated by Django 2.2.1 on 2019-06-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0007_auto_20190626_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Semestre'),
        ),
    ]
