# Generated by Django 2.2.1 on 2019-06-26 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_auto_20190626_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('numero_docente', models.CharField(max_length=10, null=True)),
                ('grau_academico', models.CharField(choices=[('-----', '-----'), ('Licenciado', 'Licenciado'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor'), ('Phd', 'Phd')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Pessoa')),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('grau_academico', models.CharField(choices=[('-----', '-----'), ('Licenciado', 'Licenciado'), ('Pós-Graduação', 'Pós-Graduação'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor'), ('Phd', 'Phd')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Estudante')),
                ('docente', models.CharField(blank=True, default='--', max_length=90, null=True)),
                ('tema', models.CharField(blank=True, default='--', max_length=190, null=True)),
                ('data_entrada', models.DateField()),
                ('estado', models.CharField(blank=True, default='Recebido', max_length=30, null=True)),
                ('descricao', models.CharField(blank=True, default='--', max_length=90, null=True)),
            ],
        ),
    ]
