# Generated by Django 2.2.1 on 2019-07-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_auto_20190626_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='pessoa',
        ),
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='Horas',
            field=models.CharField(blank=True, default='--', max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
