# Generated by Django 2.2.1 on 2019-07-10 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0012_auto_20190710_0317'),
        ('secretaria', '0011_auto_20190709_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monografia',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='core_help.Especialidade'),
        ),
    ]
