# Generated by Django 2.2.1 on 2019-07-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0013_auto_20190710_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='ano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, parent_link=True, to='core_help.Ano'),
        ),
    ]
