# Generated by Django 2.2.1 on 2019-07-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0015_modulo_disciplina_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo_disciplina',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=19, null=True),
        ),
        migrations.AddField(
            model_name='monografia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='monografia'),
        ),
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
        ),
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='nome',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='descricao',
            field=models.CharField(default='Recebido', max_length=30),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='residencia',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
