# Generated by Django 2.2.1 on 2019-07-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0016_auto_20190714_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerar_Numero_Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='monografia',
            name='descricao',
        ),
    ]
