# Generated by Django 2.2.1 on 2019-07-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0018_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
        ),
    ]
