# Generated by Django 2.2.1 on 2019-07-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0019_auto_20190714_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='numero_estudante',
            field=models.CharField(blank=True, default='Null', max_length=30, null=True),
        ),
    ]
