# Generated by Django 2.2.1 on 2019-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0021_auto_20190715_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='numero_estudante',
            field=models.CharField(blank=True, default='NULL', max_length=30, null=True),
        ),
    ]
