# Generated by Django 2.2.1 on 2019-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0023_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='data_registo_automatico',
            field=models.DateField(auto_now=True),
        ),
    ]
