# Generated by Django 2.2.1 on 2019-07-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0024_auto_20190717_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos'),
            preserve_default=False,
        ),
    ]
