# Generated by Django 2.2.1 on 2019-07-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0025_auto_20190717_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='especialidade',
        ),
    ]
