# Generated by Django 2.2.1 on 2019-07-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0026_remove_nota_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro (a)', 'solteiro (a)'), ('Casado (a)', 'casado (a)'), ('Viuvo (a)', 'viuvo (a)')], max_length=20),
        ),
    ]
