# Generated by Django 2.2.1 on 2019-07-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0027_auto_20190728_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Matricula'),
            preserve_default=False,
        ),
    ]
