# Generated by Django 2.2.1 on 2019-08-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0014_municipio'),
        ('secretaria', '0029_auto_20190731_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Municipio'),
            preserve_default=False,
        ),
    ]
