# Generated by Django 2.2.1 on 2019-08-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0030_pessoa_municipio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='curso',
        ),
    ]
