# Generated by Django 2.2.1 on 2019-10-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_help', '0015_descricao_nota'),
        ('secretaria', '0033_remove_modulo_disciplina_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='ano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Ano'),
        ),
        migrations.AddField(
            model_name='nota',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Semestre'),
        ),
    ]
