# Generated by Django 2.2.1 on 2019-10-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0034_auto_20191011_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_final_Monografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Estudante')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos')),
                ('nota', models.CharField(max_length=2)),
                ('descricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Descricao_Nota')),
                ('data_entrada', models.DateField()),
                ('data_registo_automatico', models.DateField(auto_now=True)),
            ],
        ),
    ]
