# Generated by Django 2.2.1 on 2019-10-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0035_nota_final_monografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota_final_monografia',
            old_name='data_entrada',
            new_name='data_defesa',
        ),
    ]
