# Generated by Django 2.2.1 on 2019-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0036_auto_20191014_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_final_monografia',
            name='data_defesa',
            field=models.CharField(max_length=14),
        ),
    ]
