# Generated by Django 2.2.1 on 2019-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0038_auto_20191015_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_final_monografia',
            name='data_defesa',
            field=models.CharField(max_length=14),
        ),
    ]
