# Generated by Django 2.2.1 on 2019-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0039_auto_20191015_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_final_monografia',
            name='data_defesa',
            field=models.DateField(),
        ),
    ]
