# Generated by Django 2.2.1 on 2019-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0040_auto_20191015_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='Horas',
            field=models.CharField(blank=True, default='--', max_length=20, null=True),
        ),
    ]
