# Generated by Django 2.2.1 on 2019-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0041_auto_20191027_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo_disciplina',
            name='Horas',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
