# Generated by Django 2.2.1 on 2019-12-07 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0045_remove_estudante_curso_numero_estudante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaves_Modulo_Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Modulo_Disciplina')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Cursos')),
            ],
        ),
    ]
