# Generated by Django 2.2.1 on 2019-12-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0047_auto_20191208_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaves_Modulo_AnoSemestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Ano')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Semestre')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Modulo_Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Chaves_Modulo_Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core_help.Especialidade')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Modulo_Disciplina')),
            ],
        ),
    ]
