# Generated by Django 2.2.1 on 2019-12-14 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0051_auto_20191212_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='modulo',
        ),
        migrations.AddField(
            model_name='nota',
            name='modulo_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='secretaria.Chaves_Modulo_Curso'),
            preserve_default=False,
        ),
    ]
